In [1]:
import transformers
print(transformers.__version__)

/Users/anishsoni/anaconda3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/anishsoni/anaconda3/lib/python3.10/site-packages/huggingface_hub/utils/_runtime.py:185: UserWarning: Pydantic is installed but cannot be imported. Please check your installation. `huggingface_hub` will default to not using Pydantic. Error message: '{e}'
  warnings.warn(


4.39.1


### Importing the Libraries

In [2]:
!pip install librosa
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
import numpy as np

### Load Pretrained Model

In [3]:


tokenizer = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You sho

### Load Audio File

In [4]:
audio, sampling_rate = librosa.load('audio2.m4a', sr=16000)

/var/folders/7f/7tqk6h_s4kj09qwljz25pppr0000gn/T/ipykernel_81584/693630973.py:1: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sampling_rate = librosa.load('audio2.m4a', sr=16000)
/Users/anishsoni/anaconda3/lib/python3.10/site-packages/librosa/core/audio.py:183: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [5]:
audio, sampling_rate

(array([ 1.07660890e-06, -1.17009040e-06,  1.12084672e-06, ...,
        -2.00128802e-12,  1.27613475e-11,  9.26747568e-12], dtype=float32),
 16000)

### Play the audio

In [6]:
display.Audio('audio2.m4a', autoplay = True)

### Speech to Text

In [7]:


input_values = tokenizer(audio, return_tensors = 'pt').input_values
input_values

It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.


tensor([[0.0004, 0.0004, 0.0004,  ..., 0.0004, 0.0004, 0.0004]])

In [8]:
input_values = tokenizer(audio, return_tensors = 'pt').input_values
input_values

It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.


tensor([[0.0004, 0.0004, 0.0004,  ..., 0.0004, 0.0004, 0.0004]])

#### Store logits (non-normalised predictions)

In [9]:
logits = model(input_values).logits
logits

tensor([[[ 12.8706, -26.8070, -26.5690,  ...,  -7.2395,  -7.3453,  -7.6447],
         [ 12.4742, -26.5900, -26.3720,  ...,  -7.2724,  -6.9627,  -7.4181],
         [ 12.9114, -26.7893, -26.5507,  ...,  -7.2103,  -7.3575,  -7.7429],
         ...,
         [ 13.4797, -27.7836, -27.4969,  ...,  -7.5379,  -7.5912,  -7.9146],
         [ 13.4874, -27.8826, -27.6168,  ...,  -7.6195,  -7.6742,  -7.9923],
         [ 13.4662, -27.9084, -27.6467,  ...,  -7.6533,  -7.6553,  -8.0336]]],
       grad_fn=<ViewBackward0>)

#### Store prediction id's

In [10]:
#passing the logit values to softmax
predicted_ids = torch.argmax(logits, dim =-1)

In [11]:
# pass the prediction to the tokeniser
transcriptions = tokenizer.decode(predicted_ids[0])

In [12]:
transcriptions

"HEE WHAT'S UP ARE YOU DOING"